/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  final String? code;
  final String? message;
  final String? prefix;

  AppException([this.code, this.message, this.prefix]);

  @override
  String toString() {
    return '$prefix$message';
  }
}
